version: 2.1

commands:
  install:
    description: Echo message
    steps:
      - run:
          name: Install
          command: |
              curl -L "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o ~/docker-compose
              chmod +x ~/docker-compose
              sudo mv ~/docker-compose /usr/local/bin/docker-compose
  login:
    description: Login
    steps:
      - run:
          name: Login as theblackdang
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  buildtagpush:
    description: Build, tag and push images
    steps:
      - run:
          name: Build, tag and push 4 images in this project
          command: |
            docker-compose -f docker-compose-build.yaml build --parallel
            docker tag udagram-api-feed theblackdang/udagram-api-feed:udacity
            docker tag udagram-frontend theblackdang/udagram-frontend:udacity
            docker tag udagram-api-user theblackdang/udagram-api-user:udacity
            docker tag reverseproxy theblackdang/reverseproxy:udacity
            docker push theblackdang/udagram-api-feed:udacity
            docker push theblackdang/udagram-frontend:udacity
            docker push theblackdang/udagram-api-user:udacity
            docker push theblackdang/reverseproxy:udacity

jobs:
  install:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - install
  login:
    docker:
      - image: cimg/python:3.11.4
    steps:
      - checkout
      - login
  buildtagpush:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - buildtagpush

workflows:
  default:
    jobs:
      - install
      - login:
          requires: [install]
      - buildtagpush:
          requires: [login]
