version: 2.1

commands:
  install:
    description: Echo message
    steps:
      - run:
          name: Install
          command: |
              echo "Install something..."
  build:
    description: Build docker images
    steps:
      - run:
          name: Build 4 images in this project
          command: |
            sudo dockerd
            # systemctl start docker
            docker build -t udagram-api-feed ./udagram-api-feed
            docker build -t udagram-frontend ./udagram-frontend
            docker build -t udagram-api-user ./udagram-api-user
            docker build -t reverseproxy ./udagram-reverseproxy
  tag:
    description: Tag images
    steps:
      - run:
          name: Tag 4 images being built in previous step
          command: |
            $TAG="udacity"
            docker tag udagram-api-feed theblackdang/udagram-api-feed:$TAG
            docker tag udagram-frontend theblackdang/udagram-frontend:$TAG
            docker tag udagram-api-user theblackdang/udagram-api-user:$TAG
            docker tag reverseproxy theblackdang/reverseproxy:$TAG
  login:
    description: Login
    steps:
      - run:
          name: Login as theblackdang
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  push:
    description:  Push images
    steps:
      - run:
          name: Push 4 images
          command: |
            docker push theblackdang/udagram-api-feed:$TAG
            docker push theblackdang/udagram-frontend:$TAG
            docker push theblackdang/udagram-api-user:$TAG
            docker push theblackdang/reverseproxy:$TAG

jobs:
  install:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - install
  login:
    docker:
      - image: cimg/python:3.11.4
    steps:
      - checkout
      - login
  build:
    docker:
      - image: bayesimpact/circleci
    steps:
      - checkout
      - build
  tag:
    docker:
      - image: cimg/python:3.11.4
    steps:
      - checkout
      - build
  push:
    docker:
      - image: cimg/python:3.11.4
    steps:
      - checkout
      - push

workflows:
  default:
    jobs:
      - install
      - login:
          requires: [install]
      - build:
          requires: [login]
      - tag:
          requires: [build]
      - push:
          requires: [tag]
      
