version: 2.1

commands:
  install:
    description: Echo message
    steps:
      - run:
          name: Install
          command: |
              curl -L "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o ~/docker-compose
              chmod +x ~/docker-compose
              sudo mv ~/docker-compose /usr/local/bin/docker-compose
  login:
    description: Login
    steps:
      - run:
          name: Login as theblackdang
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  build:
    description: Build, tag and push images
    steps:
      - run:
          name: Build, tag and push 4 images in this project
          command: |
            docker-compose -f docker-compose-build.yaml build --parallel
            # docker tag udagram-api-feed theblackdang/udagram-api-feed:udacity
            # docker tag udagram-frontend theblackdang/udagram-frontend:udacity
            # docker tag udagram-api-user theblackdang/udagram-api-user:udacity
            # docker tag reverseproxy theblackdang/reverseproxy:udacity
            
  push:
    description: Push 4 images
    steps:
      - run:
          name: Push 4 images
          command: |
            docker push theblackdang/udagram-api-feed:udacity
            docker push theblackdang/udagram-frontend:udacity
            docker push theblackdang/udagram-api-user:udacity
            docker push theblackdang/reverseproxy:udacity

jobs:
  allinone:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - install
      - build
      - login
      - push

workflows:
  default:
    jobs:
      - allinone