apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: hpa-project3-deployment
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: hpa-project3-deployment
 minReplicas: 2
 maxReplicas: 3
 targetCPUUtilizationPercentage: 50